[data]
  dir = 'site'
  gamesFile = 'public/games.json'
  hashFile = 'src/assets/hash.json'
  initFile = 'src/assets/init.json'

[extended]
  dir = 'cli'
  dataFile = 'extended-data.json'

[image]
  dir = 'site/src/img/games'

  [image.thumbnail]
  width = 350
  height = 250

  [image.fullsize]
  width = 600
